### ISSUE TITLE
Adding a coloured outline around regions in ggseg3d

### ISSUE THREAD

**Issue by ckelly5** [ggseg/ggseg3d#11]
Hi,
I have really been enjoying using ggseg3d! I'm wondering if it is possible to colour the edges of brain regions in ggseg3d? I believe this is possible in ggseg, using the colour="black" option (or any other colour). But I haven't been able to find a similar option in ggseg3d. I'm sorry if I missed it. I'd really appreciate any thoughts or help with this! 
Thanks,
Claire

**Comment by drmowinckels** [comment]
Hi!

Thanks for enjoying our tool. Since ggseg3d is made of lots and lots of triangles (mesh grid), colouring the edges (rather than the face as we do by default), will colour the edge of all the individual triangles, not just the outer edges of the entire mesh for a region. So I'm afraid what you are asking for is not possible using ggseg3d.

all the best.
