### ISSUE TITLE
Adding points 

### ISSUE THREAD

**Issue by jaromilfrossard** [ggseg/ggseg3d#5]
Hello,

Is there a way to add points in a ggseg3d() plot?

I have intracranial EEG data and I would like to vizualise the electrodes in space with an atlas of the brain region in background.

Thanks!

**Comment by drmowinckels** [comment]
I really want to say yes, because I am quite wire this should be possible within the plotly framework.
I didnt have much time to play about with it today, but if you try googling something like `combining plotly mesh3d and scatter3d` or the like, that should take you in the right direction.

My gut feeling tells me you should be able to use 

```
ggseg() %>%
  add_trace(electrode_position_data, ~x, ~y, ~z, marker="scatter3d") 
```

or something like that.

**Comment by mwvoss** [comment]
@jaromilfrossard  I'm looking for the same functionality. Did you get a working version of this?

**Comment by jaromilfrossard** [comment]
You can add point using:


``
ggseg3d()%>%
  add_trace(x = 50, y = 00, z = 80, type = "scatter3d", mode = "markers", inherit = F) 
``

However, I did not investidate further as I had some problems with the scales (relatively to gged3d() ) of the data I wanted to plot.
